name: "Demo: Use local action"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Debug: list action directory"
        run: |
          echo "CWD: $(pwd)"
          ls -la .github || true
          ls -la .github/actions || true
          ls -la .github/actions/say-hello || true

      - name: Run local say-hello action
        id: say
        uses: ./.github/actions/say-hello
        with:
          name: Fabio
          loud: "true"

      - name: Show greeting output
        run: "echo \"Greeting from action: ${{ steps.say.outputs.greeting }}\""